#!/bin/bash

echo "Enter Target IP or IP Range (e.g., 192.168.1.0/24 for a subnet):"
read -p "Target: " IP_IN
echo "Target IP is $IP_IN"
echo "[1] TCP SYN PORT SCAN"
echo "[2] TCP CONNECT PORT SCAN"
echo "[3] UDP PORT SCAN"
echo "[4] TCP ACK PORT SCAN"
echo "[5] PING SWEEP SCAN"
echo "[6] XMAS SCAN"
echo "[7] PING SWEEP WITH HOSTS PORTS"
echo "[8] NULL SCAN"
echo "[9] FIN SCAN"
echo "[10] OS FINGERPRINTING SCAN"
echo "[11] QUIT"
read -p "Choose an option: " NM_SEL

case $NM_SEL in
    1)
        nmap -sS "$IP_IN"
        ;;
    2)
        nmap -sT "$IP_IN"
        ;;
    3)
        nmap -sU "$IP_IN"
        ;;
    4)
        nmap -sA "$IP_IN"
        ;;
    5)
        nmap -sP "$IP_IN"
        ;;
    6)
        nmap -sX "$IP_IN"
        ;;
    7)
        nmap -Pn "$IP_IN"
        ;;
    8)
        nmap -sN "$IP_IN"
        ;;
    9)
        nmap -sF "$IP_IN"
        ;;
    10)
        nmap -sV -O -v "$IP_IN"
        ;;
    11)
        exit
        ;;
    *)
        echo "Invalid option. Please enter a number between 1 and 11."
        ;;
esac
